### ISSUE TITLE
card is empty

### ISSUE THREAD

**Issue by nf-gh057** [HAuser1234/homeassistant-local-weather-forecast#4]
I can't make it work. I installed mushroom and vertical stack in card, did anything like said in "instalation", but my card is empty. Tried to check developer tools for entities, but with name "local" there is only person.local_view, so it looks like it's not loading. 

![obraz](https://github.com/HAuser1234/homeassistant-local-weather-forecast/assets/54669248/43cc9c97-3537-43de-9e2b-82bf27ecfde2)
![obraz](https://github.com/HAuser1234/homeassistant-local-weather-forecast/assets/54669248/7d92dce5-4609-4603-9208-c4503d25a88c)
![obraz](https://github.com/HAuser1234/homeassistant-local-weather-forecast/assets/54669248/60da314d-6432-47ca-b0ab-468a343a8c56)

Already tried to enter '0' to config, to see if anything will change, but without effect. Restarted several times.

 Home Assistant 2023.9.2 
Supervisor 2023.09.2 
Operating System 10.5
Frontend 20230911.0 - latest 

From log i'm getting this error:

`

Logger: homeassistant.helpers.event
Source: helpers/template.py:570
First occurred: 9:46:19 PM (110 occurrences)
Last logged: 9:58:49 PM

    Error while processing template: Template<template=({{states.sensor.local_forecast_zambretti_detail.attributes.icons[1]}}) renders=38>
    Error while processing template: Template<template=(~ {{states.sensor.local_forecast_zambretti_detail.attributes.second_time[0]}}) renders=38>
    Error while processing template: Template<template=(Rain: {{states.sensor.local_forecast_zambretti_detail.attributes.rain_prob[1]}}% {%if states.sensor.local_forecast.attributes.forecast_temp_short[1] == 1%}{{states.sensor.local_forecast.attributes.forecast_temp_short[0]}}°C{%endif%}) renders=38>
    Error while processing template: Template<template=(forecast: {{states.sensor.local_forecast.attributes.forecast_zambretti[0]}}) renders=38>
    Error while processing template: Template<template=(Pressure: {{states.sensor.local_forecast.attributes.forecast_pressure_trend[0]}} {{states.sensor.local_forecast_pressurechange.state}} hpa in 3h) renders=38>

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 568, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2198, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
jinja2.exceptions.UndefinedError: 'None' has no attribute 'state'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 694, in async_render_to_info
    render_info._result = self.async_render(
                          ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 570, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: UndefinedError: 'None' has no attribute 'state'

`

I'll be gratefull for any advices.

**Comment by nf-gh057** [comment]
I think I've found where the problem is - my vertical-stack-in-card was not configured properly.
